name: build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'amd64', 'arm64' ]
        
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v1
 
    - name: Build Docker Image
      run: |
        docker build \
          --platform="linux/${{ matrix.platform }}" \
          --tag my-image-name:"${{ matrix.platform }}" \
          --file Dockerfile .
    - name: Load Docker Image
      run: |
        nix build .#dockerImage
        docker load < result
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: my-image-name:${{ matrix.platform }}
